### ISSUE TITLE
Prevent password leaks

### ISSUE THREAD

**Issue by Znegl** [stephenkr/nuxt-password-protect#44]
When setting a password through `nuxt.config.js`, I can see the raw text password in `/_nuxt/app.js` when running a development server and in one of the JS files with random names when running a production server.
This seems to defeat the purpose of a secret password, when anyone can go through the publicly available code and search for the string "password".

**Comment by stephenkr** [comment]
Hi @Znegl thank you for creating the issue.

This is the joys of having this module work in the client side, theres no way to truely protect the password from the frontend. The intention of this module was just protect the website in a simple and basic way. I built it for a website to share some work in progress with a client.

I'll look into restricting it only for the server and using `privateRuntimeConfig` instead - more here https://nuxtjs.org/docs/2.x/directory-structure/nuxt-config#privateruntimeconfig

Since this module is gaining more popularity, lets try and secure it futher.

Thank you again for the issue and for helping to make it better :)

**Comment by Znegl** [comment]
Nice trick! Luckily i don't need anything more secure right now, but I'll gladly try to help looking into a more secure solution when my project is fully running and I have a little time to spare.
